### ISSUE TITLE
questions on 2020 upping this

### ISSUE THREAD

**Issue by ensemblebd** [vlasky/meteor-mysql#1]
First let me say, AMAZING package. Have done countless hours of research on best approach, and this package is the best available right now. 

I have a couple questions:

1. your thoughts on how best to upgrade this to support mysql 8.0?  
Seems to give out ETIMEOUT errors on init, as compared to a same-config 5.7 setup. (and it's not native pass non-default issue)
I realize this may be more in the realm of [numtel] dependency chain. 

2. How would you recommend going about retrofitting official MDG packages, such as:
 - accounts-base
 - accounts-password
 - accounts-ui
They seem to be fairly "integrated" into a mongo backend expectation.  I'd love to keep existing logistics, but swap out the mongo side by using local [packages] to adjust them. 
Or would you instead recommend to not use those, and "roll your own" via meteor methods and exposed subscriptions?
Aka, start fresh for accounts, or dig deep into existing mdg?

Flying solo here, so hoping you might see this ticket? Thank you

**Comment by vlasky** [comment]
Hello @ensemblebd. My responses:

1. Please share your error message output.

Also, which release of MySQL 8.0 are you using? My recommendation is Percona Server.

2. The accounts packages are very tightly coupled to MongoDB and require much effort to port to MySQL.

These are the alternatives that I and others have used in production apps:

*Roll your own (as you mentioned), by setting and checking the value of this.userId in Meteor methods and publications
*Use the accounts packages with MongoDB alongside but separate to MySQL
*Use MySQL to store the user account data and use it to populate the MongoDB collections upon startup and keep the data in sync during runtime.

**Comment by ensemblebd** [comment]
timeout issue was silly, timeout setting, when debugger attached it took too long to build >.<

Awesome thank you, that is definitely helpful! 
Thank you again for all your work on this package. Kept seeing it come up in discussions with you and others, and it works really well
